FROM adoptopenjdk/openjdk11

MAINTAINER Swaroop HS "swhsaws@gmail.com"

EXPOSE 8080

WORKDIR /usr/local/bin/

COPY ./target/SpringSAMLWeb-0.0.1-SNAPSHOT.jar webapp.jar

CMD ["java", "-jar","webapp.jar"]